# 100 задач по numpy

Задачи собраны из рассылки numpy, Stack Overflow и документации.
Сложность отмечена звёздами: ★☆☆ — ★★★.

Первая ячейка подключает помощники: `question(n)` — условие, `hint(n)` — подсказка,
`pick()` — случайная задача. Решение пиши в пустой ячейке под условием.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)
*Импортировать пакет numpy под именем `np`*


In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
*Вывести версию numpy и её конфигурацию*


In [5]:
print(np.__version__)
print(np.show_config())

2.5.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.13/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.13/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.34.106.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.34.106.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.13/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.13/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.34.106.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.34.106.0
Compilers:
  c:
    comm

#### 3. Create a null vector of size 10 (★☆☆)
*Создать нулевой вектор размера 10*


In [6]:
zeros_vector = np.zeros(10)
print(zeros_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
*Как узнать, сколько памяти занимает массив*


In [8]:
zeros_vector = np.zeros((10, 10))
print(zeros_vector)
print()
print(zeros_vector.nbytes)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
*Как получить документацию функции numpy add из командной строки?*


In [9]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
*Создать нулевой вектор размера 10, у которого пятый элемент равен 1*


In [10]:
zeros_vector = np.zeros(10)
print(zeros_vector)
zeros_vector[4] = 1
print(zeros_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
*Создать вектор со значениями от 10 до 49*


In [11]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
*Развернуть вектор (первый элемент становится последним)*


In [15]:
vector = np.arange(10)
print(vector)
reverse_vector = np.flip(vector)
print(reverse_vector)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
*Создать матрицу 3x3 со значениями от 0 до 8*


In [17]:
vector = np.arange(9)
print(vector)
matrix = vector.reshape(3,3)
print(matrix)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
*Найти индексы ненулевых элементов в [1,2,0,0,4,0]*


In [18]:
vector = np.array([1, 2, 0, 0, 4, 0])
result = []
for i in range(len(vector)):
    if vector[i] != 0:
        result.append(i)
print(result)

[0, 1, 4]


In [29]:
vector = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(vector))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)
*Создать единичную матрицу 3x3*


In [28]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
*Создать массив 3x3x3 со случайными значениями*


In [21]:
random_matrix = np.random.rand(3,3,3)
print(random_matrix)

[[[0.4255613  0.9782614  0.61099916]
  [0.11315981 0.69912659 0.32693676]
  [0.92665055 0.89550284 0.43773137]]

 [[0.14777465 0.14721626 0.79518698]
  [0.70283204 0.46455682 0.80272468]
  [0.48525138 0.37807954 0.08542944]]

 [[0.29651577 0.2828904  0.4057901 ]
  [0.41987305 0.61787749 0.26627464]
  [0.47147788 0.98184847 0.08111264]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
*Создать массив 10x10 со случайными значениями и найти минимум и максимум*


In [23]:
random_matrix = np.random.rand(10, 10)
print(random_matrix)
print()
print(np.min(random_matrix))
print(np.max(random_matrix))

[[0.67514462 0.23985941 0.42067672 0.54028885 0.89946312 0.96372665
  0.70419349 0.88312134 0.80878671 0.01143313]
 [0.51970636 0.96672266 0.34499417 0.22993103 0.10660713 0.18750556
  0.09305286 0.33055615 0.33350996 0.5584595 ]
 [0.52484113 0.65986209 0.2584886  0.54376789 0.34740695 0.31927416
  0.63397081 0.361828   0.53810031 0.39253002]
 [0.62332031 0.08222235 0.92703175 0.73854106 0.93806453 0.54508323
  0.02519501 0.13032652 0.98815423 0.75329477]
 [0.16744927 0.61206257 0.2007241  0.88850946 0.95337747 0.48516631
  0.97471829 0.90434817 0.67030477 0.29432708]
 [0.61792668 0.34690058 0.99859875 0.05934813 0.61880274 0.0121041
  0.55666099 0.62178195 0.15088228 0.33733099]
 [0.01251731 0.78747794 0.82483303 0.63292562 0.43064189 0.66879169
  0.27203561 0.07489613 0.99990707 0.90529933]
 [0.15884315 0.64277367 0.80370281 0.05264471 0.03398416 0.93394078
  0.60039682 0.99412687 0.52350133 0.17465724]
 [0.39815498 0.320871   0.81817988 0.14214723 0.15097503 0.76272657
  0.33756649 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
*Создать случайный вектор размера 30 и найти его среднее значение*


In [24]:
random_vector = np.random.rand(30)
print(random_vector)
print(np.mean(random_vector))

[0.99232282 0.40060351 0.91905697 0.70910347 0.83711849 0.56835474
 0.65493279 0.28958309 0.26533669 0.52884113 0.89587962 0.89047006
 0.02028639 0.87253945 0.97264273 0.69259169 0.44297333 0.59345524
 0.1527141  0.28544296 0.33080426 0.24241649 0.74340097 0.45206098
 0.34209415 0.78696983 0.57028569 0.27066502 0.33737698 0.21132112]
0.5423881580320906


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
*Создать двумерный массив с единицами по краю и нулями внутри*


In [26]:
rows, cols = 10, 10
array = np.ones((rows, cols))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
*Как добавить рамку из нулей вокруг существующего массива?*


#### 17. What is the result of the following expression? (★☆☆)
*Каким будет результат следующих выражений?*

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
*Создать матрицу 5x5 со значениями 1,2,3,4 под главной диагональю*


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
*Создать матрицу 8x8 и заполнить её в шахматном порядке*


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
*Дан массив формы (6,7,8). Каков индекс (x,y,z) сотого элемента?*


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
*Создать шахматную матрицу 8x8 с помощью функции tile*


#### 22. Normalize a 5x5 random matrix (★☆☆)
*Нормализовать случайную матрицу 5x5*


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
*Создать пользовательский dtype, описывающий цвет четырьмя беззнаковыми байтами (RGBA)*


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
*Перемножить матрицу 5x3 на матрицу 3x2 (настоящее матричное произведение)*


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
*Дан одномерный массив: поменять знак у всех элементов от 3 до 8, не создавая копию*


#### 26. What is the output of the following script? (★☆☆)
*Что выведет следующий скрипт?*

```python
# Author: Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
*Дан целочисленный вектор Z. Какие из этих выражений допустимы?*

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```


#### 28. What are the result of the following expressions? (★☆☆)
*Каковы результаты следующих выражений?*

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```


#### 29. How to round away from zero a float array ? (★☆☆)
*Как округлить массив чисел с плавающей точкой в сторону от нуля?*


#### 30. How to find common values between two arrays? (★☆☆)
*Как найти общие значения двух массивов?*


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
*Как отключить все предупреждения numpy (не рекомендуется)?*


#### 32. Is the following expressions true? (★☆☆)
*Верно ли следующее выражение?*

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
*Как получить даты вчера, сегодня и завтра?*


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
*Как получить все даты июля 2016 года?*


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
*Как вычислить ((A+B)*(-A/2)) на месте, без копий?*


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
*Извлечь целую часть массива случайных положительных чисел четырьмя разными способами*


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
*Создать матрицу 5x5, в каждой строке которой значения от 0 до 4*


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
*Дана генераторная функция, возвращающая 10 целых чисел: построить из неё массив*


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
*Создать вектор размера 10 со значениями от 0 до 1, не включая границы*


#### 40. Create a random vector of size 10 and sort it (★★☆)
*Создать случайный вектор размера 10 и отсортировать его*


#### 41. How to sum a small array faster than np.sum? (★★☆)
*Как сложить элементы маленького массива быстрее, чем np.sum?*


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)
*Даны два случайных массива A и B: проверить, равны ли они*


#### 43. Make an array immutable (read-only) (★★☆)
*Сделать массив неизменяемым (только для чтения)*


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
*Дана случайная матрица 10x2 с декартовыми координатами: перевести их в полярные*


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
*Создать случайный вектор размера 10 и заменить максимальное значение нулём*


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
*Создать структурированный массив с координатами `x` и `y`, покрывающими область [0,1]x[0,1]*


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
*Даны массивы X и Y: построить матрицу Коши C (Cij = 1/(xi - yj))*


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)
*Вывести минимальное и максимальное представимые значения для каждого скалярного типа numpy*


#### 49. How to print all the values of an array? (★★☆)
*Как вывести все значения массива без сокращений?*


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
*Как найти в векторе значение, ближайшее к заданному числу?*


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
*Создать структурированный массив, представляющий позицию (x,y) и цвет (r,g,b)*


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
*Дан случайный вектор формы (100,2) с координатами: найти попарные расстояния между точками*


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?
*Как преобразовать массив float32 в массив int32 на месте?*


#### 54. How to read the following file? (★★☆)
*Как прочитать следующий файл?*

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
*Что является аналогом enumerate для массивов numpy?*


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
*Сгенерировать двумерный массив, похожий на гауссиану*


#### 57. How to randomly place p elements in a 2D array? (★★☆)
*Как случайным образом разместить p элементов в двумерном массиве?*


#### 58. Subtract the mean of each row of a matrix (★★☆)
*Вычесть из каждой строки матрицы её среднее значение*


#### 59. How to sort an array by the nth column? (★★☆)
*Как отсортировать массив по n-му столбцу?*


#### 60. How to tell if a given 2D array has null columns? (★★☆)
*Как определить, есть ли в двумерном массиве нулевые столбцы?*


#### 61. Find the nearest value from a given value in an array (★★☆)
*Найти в массиве значение, ближайшее к заданному*


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
*Даны массивы форм (1,3) и (3,1): как вычислить их сумму с помощью итератора?*


#### 63. Create an array class that has a name attribute (★★☆)
*Создать класс массива с атрибутом name*


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
*Дан вектор: как прибавить 1 к каждому элементу по индексам из второго вектора (осторожно с повторяющимися индексами)?*


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
*Как накопить элементы вектора X в массив F по списку индексов I?*


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
*Дано изображение формы (w,h,3) типа ubyte: посчитать количество уникальных цветов*


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
*Дан четырёхмерный массив: как получить сумму сразу по двум последним осям?*


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
*Дан одномерный вектор D: как вычислить средние по его подмножествам, используя вектор S той же длины с индексами подмножеств?*


#### 69. How to get the diagonal of a dot product? (★★★)
*Как получить диагональ матричного произведения?*


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
*Дан вектор [1, 2, 3, 4, 5]: как построить новый вектор, вставив по 3 нуля между соседними значениями?*


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)
*Дан массив формы (5,5,3): как умножить его на массив формы (5,5)?*


#### 72. How to swap two rows of an array? (★★★)
*Как поменять местами две строки массива?*


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
*Даны 10 троек, описывающих 10 треугольников с общими вершинами: найти множество уникальных отрезков, из которых состоят все треугольники*


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
*Дан отсортированный массив C, полученный как bincount: как построить массив A такой, что np.bincount(A) == C?*


#### 75. How to compute averages using a sliding window over an array? (★★★)
*Как вычислить средние скользящим окном по массиву?*


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
*Дан одномерный массив Z: построить двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая следующая сдвинута на 1 (последняя — (Z[-3],Z[-2],Z[-1]))*


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
*Как инвертировать логическое значение или сменить знак у float на месте?*


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
*Даны два набора точек P0, P1, задающих прямые на плоскости, и точка p: как вычислить расстояние от p до каждой прямой i (P0[i],P1[i])?*


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
*Даны два набора точек P0, P1, задающих прямые, и набор точек P: как вычислить расстояние от каждой точки j до каждой прямой i?*


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
*Дан произвольный массив: написать функцию, извлекающую подмассив фиксированной формы с центром в заданном элементе (дополняя значением `fill`, если нужно)*


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
*Дан массив Z = [1,2,...,14]: как получить массив R = [[1,2,3,4], [2,3,4,5], ..., [11,12,13,14]]?*


#### 82. Compute a matrix rank (★★★)
*Вычислить ранг матрицы*


#### 83. How to find the most frequent value in an array?
*Как найти самое частое значение в массиве?*


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
*Извлечь все смежные блоки 3x3 из случайной матрицы 10x10*


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
*Создать подкласс двумерного массива, для которого Z[i,j] == Z[j,i]*


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
*Даны p матриц формы (n,n) и p векторов формы (n,1): как вычислить сумму p матричных произведений за один раз? (результат формы (n,1))*


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
*Дан массив 16x16: как получить суммы по блокам 4x4?*


#### 88. How to implement the Game of Life using numpy arrays? (★★★)
*Как реализовать игру «Жизнь» на массивах numpy?*


#### 89. How to get the n largest values of an array (★★★)
*Как получить n наибольших значений массива?*


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)
*Дано произвольное число векторов: построить их декартово произведение (все комбинации всех элементов)*


#### 91. How to create a record array from a regular array? (★★★)
*Как создать record array из обычного массива?*


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
*Дан большой вектор Z: возвести его в куб тремя разными способами*


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain at least one element of each row of B regardless of the order of the elements in B?
*Даны массивы A и B форм (8,3) и (2,2): как найти строки A, содержащие хотя бы один элемент из каждой строки B, независимо от порядка элементов в B?*


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
*Дана матрица 10x3: извлечь строки, в которых не все значения одинаковы (например, [2,2,3])*


#### 95. Convert a vector of ints into a matrix binary representation (★★★)
*Преобразовать вектор целых чисел в матрицу их двоичных представлений*


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
*Дан двумерный массив: как извлечь уникальные строки?*


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
*Даны векторы A и B: записать через einsum аналоги inner, outer, sum и mul*


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
*Дан путь, заданный векторами (X,Y): как разбить его на равноудалённые точки?*


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
*Даны целое n и двумерный массив X: выбрать из X строки, которые можно считать выборкой из мультиномиального распределения с n степенями, то есть строки только из целых чисел, сумма которых равна n*


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
*Вычислить бутстрэп-доверительный интервал 95% для среднего одномерного массива X (N раз выбрать элементы с возвращением, посчитать среднее каждой выборки и взять перцентили этих средних)*
